module.exports.CATEGORY = {
  PRODUCER: "PRODUCER",
  ARTIST: "ARTIST",
  FAN: "FAN",
  ENGINEER: "ENGINEER & OTHERS",
};

module.exports.PLAN = {
  BASIC: "BASIC",
  ADVANCE: "ADVANCE",
  PREMIUM: "PREMIUM",
  CUSTOM: "CUSTOM",
};

module.exports.ACCOUNT_STATUS = {
  ACTIVE: "ACTIVE",
  UNVERIFIED: "UNVERIFIED",
  DEACTIVATED: "DEACTIVATED",
  BLOCKED: "BLOCKED",
};

module.exports.PROJECT_TYPE = {
  MUSIC: "MUSIC",
  PODCAST: "PODCAST",
  AUDIOBOOK: "AUDIOBOOK",
  OTHER: "OTHER",
};

module.exports.PROJECT_STATUS = {
  IN_PROGRESS: "IN PROGRESS",
  ON_HOLD: "ON HOLD",
  COMPLETED: "COMPLETED",
};
